WITH SRC AS (
    SELECT DISTINCT EMP_ID, EMP_NAME, EMP_CODE--, DEVICE_NAME, DEVICE_NUM
    FROM DMS_ACCT_PRL_INS_TIME
), SRC_GROUP AS (
    SELECT EMP_ID, 
        LISTAGG(DISTINCT DEVICE_NAME, ', ') WITHIN GROUP (ORDER BY DEVICE_NAME) AS DEVICES_
    FROM (SELECT DISTINCT EMP_ID, EMP_NAME, EMP_CODE, DEVICE_NAME, DEVICE_NUM FROM DMS_ACCT_PRL_INS_TIME)
    GROUP BY EMP_ID
)
SELECT t.EMP_ID, DEVICES_ AS ORG, EMP_NAME, 2 AS GENDER, CREATE_BRANCH AS CONTACT, NULL AS EMAIL,
    TO_CHAR(NVL(CAST(aemp.CREATE_TIME AS DATE), CURRENT_DATE - 365), 'YYYY/MM/DD') AS EFFECTIVE_TIME,
    --aemp.CREATE_TIME + interval '3' year
    CURRENT_STATUS,
    --CAST((aemp.CREATE_TIME + interval '3' year) AS DATE)
    TO_CHAR(CASE WHEN CURRENT_STATUS = 'Y' AND aemp.CREATE_TIME IS NOT NULL THEN CAST((aemp.CREATE_TIME + interval '3' year) AS DATE)
        WHEN CURRENT_STATUS = 'Y' AND aemp.CREATE_TIME IS NULL THEN (CURRENT_DATE + (365*2))
        WHEN CURRENT_STATUS = 'N' THEN CURRENT_DATE - 1
        ELSE CURRENT_DATE + 365 END, 'YYYY/MM/DD') 
    AS EXPIRE_TIME,
    EMP_CODE AS CARD_NUM
FROM (
    SELECT * FROM SRC WHERE EMP_NAME IS NOT NULL
    UNION
    SELECT * FROM SRC WHERE EMP_NAME IS NULL AND EMP_ID NOT IN (SELECT EMP_ID FROM SRC WHERE EMP_NAME IS NOT NULL)    
) t
LEFT JOIN (
    SELECT AEMP_ID, FULL_NAME, AEMP_STATUS, CREATE_BRANCH, AEMP_CODE FROM DMS_ACCT_EMP WHERE AEMP_ID_GROUP LIKE 'VSAXESS%'
) e ON ':'||t.EMP_ID||':' LIKE '%:'|| e.AEMP_CODE || ':%'
LEFT JOIN 
(
    SELECT g.USER_ID, CREATE_TIME, CURRENT_STATUS, EMP_ID 
    FROM DMS_USER_REL_AEMP g LEFT JOIN
        (SELECT USER_ID, MAX(STATUS) AS CURRENT_STATUS FROM DMS_USER_REL_AEMP GROUP BY USER_ID) t ON t.USER_ID = g.USER_ID
    WHERE EMP_ID_SRC = 'DMS_ACCT_EMP'
) aemp ON e.AEMP_ID = aemp.EMP_ID
LEFT JOIN src_group ON t.EMP_ID = src_group.EMP_ID
ORDER BY EMP_NAME
